server:
  port: 9000

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Redis
  data:
    redis:
      enabled: true
      host: 127.0.0.1
      port: 6379
      connect-timeout: 5000ms
      read-timeout: 5000ms
      use-pool: true
      check-connection: true
      lettuce:
        pool:
          enabled: true
          max-active: 50
          max-idle: 10
          min-idle: 0
          max-wait: 3000ms
          min-evictable-idle-time: 60000ms
          time-between-eviction-runs: 30000ms
      topic:
        enabled: true
        event: event

# Thread Pool
task:
  executor:
    core:
      pool:
        size: 10
    max:
      pool:
        size: 15
    queue:
      capacity: 20

# RabbitMQ
rabbit:
  host: localhost
  port: 5672
  username: guest
  password: guest
  channels: 8
  queues: Cam01, Cam02, Cam03, Cam04, Cam05, Cam06, Cam07, Cam08

# --- Cvedia Instance Names / Wire Names --- #
cvedia:
  host: localhost:8080
  instance: Cam01, Cam02, Cam03, Cam04, Cam05, Cam06, Cam07, Cam08
  wire-name: NW01C001, NW01C002, NW01C003, NW01C004, NW01C005, NW01C006, NW01C007, NW01C008, NW01C009, NW01C010, NW01C011, NW01C012, NW01C013, NW01C014, NW01C015, NW01C016, NW01C017, NW01C018, NW01C019, NW01C020, NW01C021, NW01C022, NW01C023, NW01C024, NW01C025, NW01C026, NW01C027, NW01C028, NW01C029, NW01C030, NW01C031, NW01C032, NW01C033, NW01C034
